### ISSUE TITLE
usage documentation for zf3 not meaningful/correct

### ISSUE THREAD

**Issue by rogatec** [zendframework/zend-i18n-resources#20]
When using the `addTranslationFilePattern` the first parameter is given as a string in the documentation `phpArray`.

In Zend Framework 3 the `loadMessagesFromPatterns` in the `Translator` class uses this string to get the plugin from the PluginManager (in line 655).

Unfortunately this throws an exception because the PluginManager can't handle `phpArray` as a string(?).

If I explicitly use the class reference it is working.

working solution:

``` php
use Zend\I18n\Translator\Loader\PhpArray;
// [...]
$translator = new Translator();
$translator->addTranslationFilePattern(
            PhpArray::class,
            Resources::getBasePath(),
            Resources::getPatternForValidator()
);
```

Additionally I recognized that the config array should also look like this to work properly, only using a string like `MvcTranslator` didn't work:

``` php
    'service_manager' => [
        'delegators' => [
            \Zend\Mvc\I18n\Translator::class => [
                TranslatorDelegator::class,
            ],
        ],
    ],
```

Maybe to give other users a better understanding this can be adjusted?

I think the problem occurs, when using the complete zend framwork which brings other classes with the same name like those to `phpArray`

**Comment by weierophinney** [comment]
The problem is missing aliases.

In zend-servicemanager v2, we performed normalization that would transform `PhpArray`, `phpArray`, `PHPArray`, etc to `phparray`. In v3, we no longer do such normalization, which prompted us to write a number of aliases to the new service name.

So, the problem here is that we only define `phparray` as an alias, and neither of `PhpArray` or `phpArray`. Would you be willing to create a pull request adding these two aliases to `src/Translator/LoaderPluginManager.php`?

**Comment by rogatec** [comment]
@weierophinney hope the PR is correct 🐙 

btw. I saw this in the `composer.json` : `"fabpot/php-cs-fixer": "1.7.*",` <-- should this also be changed to `"friendsofphp/php-cs-fixer":"^1.12",` ?

**Comment by weierophinney** [comment]
> btw. I saw this in the composer.json : "fabpot/php-cs-fixer": "1.7.*", <-- should this also be changed to "friendsofphp/php-cs-fixer":"^1.12", ?

No, it should be changed to `"squizlabs/php_codesniffer": "^2.6.2"` :angry: (because phpcs at least doesn't introduce new arbitrary, non-related rules that lead to CS "failures" on new versions...)

**Comment by rogatec** [comment]
obviously there is already a pull request by @samsonasik with https://github.com/zendframework/zend-i18n/pull/56

**Comment by bartoszzajac** [comment]
@rogatec I suppose that `TranslatorDelegator::class` refers to file created here [https://github.com/zendframework/zend-i18n-resources/blob/master/doc/book/usage.md#automating-resource-injection](url). I put this in Application/Delegator/TranslatorDelegator.php file and changed `TranslatorDelegator::class` to `Application\Delegator\TranslatorDelegator::class` and my TranslatorDelegator is never called. What should I do?

**Comment by rogatec** [comment]
@bartoszzajac your url behind the link is broken ;)

I have a custom `TranslatorDelegator::class` which implements `DelegatorFactoryInterface`.
The `__invoke` method looks like this:

``` php
public function __invoke(ContainerInterface $container, $name, callable $callback, array $options = null)
{
    $config = $container->get('config');

    if (!isset($config['translator']['locale'])) {
        throw new InvalidArgumentException("translator/locale array part missing in global config file");
    }

    $translator = new Translator();
    $translator->addTranslationFilePattern(
        PhpArray::class,
        Resources::getBasePath(),
        Resources::getPatternForValidator()
    );
    $translator->setLocale($config['translator']['locale']);

    return new \Zend\Mvc\I18n\Translator($translator);
}
```

In the `config.module.php` of the module I'm implementing into the returned array the following part:

``` php
'service_manager' => [
    'factories' => [
        // other module factories
    ],
    'delegators' => [
        \Zend\Mvc\I18n\Translator::class => [
            TranslatorDelegator::class,
        ],
    ],
],
```

Lastly to get things working I implemented the `onBootstrap` method in my `Module.php` class.

``` php
public function onBootstrap(MvcEvent $event)
{
    /** @var Translator $translator */
    $translator = $event->getApplication()->getServiceManager()->get(Translator::class);
    AbstractValidator::setDefaultTranslator($translator);
}
```

I hope this can answer your question. If not please provide a little bit of your code implementation.

**Comment by bartoszzajac** [comment]
Broken link is official documentation: https://github.com/zendframework/zend-i18n-resources/blob/master/doc/book/usage.md#automating-resource-injection (I just copied this file). You did this in some different way. I need to analyse that.

**Comment by rogatec** [comment]
I have to admit, that I also tried it for several hours and the _working_ solution from the previous comment is my result :-/ I don't know if this is the correct way.

**Comment by bartoszzajac** [comment]
@rogatec can you tell what is your file structure for TranslatorDelegator?

**Comment by rogatec** [comment]
`{PROJECT_ROOT}/module/Main/src/Factory/TranslatorDelegator.php`

therefore my namespace is `namespace Main\Factory` in the `TranslatorDelegator.php`

**Comment by bartoszzajac** [comment]
Do you have 'factories' key for TranslatorDelegator in service_manager config?

**Comment by rogatec** [comment]
No, only `delegators`

``` php
'service_manager' => [
    'delegators' => [
        \Zend\Mvc\I18n\Translator::class => [
            TranslatorDelegator::class,
        ],
    ],
],
```

**Comment by bartoszzajac** [comment]
Ok it is working now. I missed onBootstrap part that you have provided. I haven't change TranslatorDelegator from documentation so it is working.

**Comment by phgeek** [comment]
Thanks a lot @rogatec!!! You saved my day.

As said at [#106 on zend-validator](https://github.com/zendframework/zend-validator/issues/106) 'phpArray' is now 'phparray'.

**Comment by 85jacek** [comment]
That's the fastest way without configuring delegators:

 ```
public function onBootstrap(MvcEvent $e)
    {
        AbstractValidator::setDefaultTranslator($e->getApplication()->getServiceManager()->get('MvcTranslator'));
    }
```
