### ISSUE TITLE
Which branch is the correct to send PRs to?

### ISSUE THREAD

**Issue by mmoll** [zendframework/zend-i18n-resources#26]
master or develop?

**Comment by weierophinney** [comment]
Master is fine for this repository. Thanks in advance!

**Comment by mmoll** [comment]
thanks!

**Comment by mmoll** [comment]
@weierophinney BTW, more or less all open PRs (except #12 which git superseded by #14) are ready to merge now, IMHO. For a project at work I would appreciate a new version of 2.5.x with #25 in it.
