### ISSUE TITLE
Wrong german translation, "pass" should be "passt"

### ISSUE THREAD

**Issue by cstoehr** [zendframework/zend-i18n-resources#33]
https://github.com/zendframework/zend-i18n-resources/blob/192aa104d818106a6b67eaf47205e5b069885040/languages/de/Zend_Validate.php#L80

 "The input does not fit the date format '%format%'" => "Die Eingabe **pass** nicht zum Datumsformat '%format%'",

Wrong translation here, should be: Die Eingabe **passt** nicht zum Datumsformat '%format%'",

**Comment by mmoll** [comment]
Please open a pull request.

**Comment by cstoehr** [comment]
#40
